### PR TITLE
Added more fonts

### PR DESCRIPTION
**Pull request by CryptoLuigi**
Just adds 11 more fonts from my version of easy_pil. Might as well merge the forks since all it does is add more font options.

### CODE REVIEW

**Comment by shahriyardx** [comment]
What will be the package install size after adding these fonts??

**Comment by CryptoLuigi** [comment]
29 mb is the final size. Also without font option it can limiting because the included fonts can't display a lot of characters for many languages. Like MS Gothic is a larger font file but it has the capability to display most characters.

**Comment by CryptoLuigi** [comment]
I deleted all the unused fonts. so its at about 23 mb now.

**Comment by shahriyardx** [comment]
> I deleted all the unused fonts. so its at about 23 mb now.

I think adding this to the main lib is a overkill, Instead I might need to make some kind of plugin system. Just like discord.ext

**Pull request closed without merging**
